name: Payment-Microservice Deploy

on:
  push:
    branches:
      - main

jobs:
  # 1. Build e validação da aplicação
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build application
        run: |
          chmod +x mvnw # Concede permissão de execução ao Maven Wrapper
          ./mvnw clean package -DskipTests=true

      - name: Upload application artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: 4fc1595f3f3711174dcac36bf06a11606b230687
          SONAR_HOST_URL: https://sonarcloud.io
        run: |
          ./mvnw sonar:sonar \
          -Dsonar.projectKey=Lucas-lds_grupo-34-restaurante-pagamento \
          -Dsonar.projectName=Grupo-34-restaurante-pagamento \
          -Dsonar.organization=lucas-lds \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=4fc1595f3f3711174dcac36bf06a11606b230687
